### ISSUE TITLE
Balance of I or J tokens are taken right away in the UI even if the transaction failed for withdrawal.

### ISSUE THREAD

**Issue by jmarrr** [Jungle-Finance/dapp-suppot#8]
**Describe the bug**
The UI balance of my I or J tokens automatically subtract the amount I wanted to withdraw even if the transaction actually failed. Happens both all withdraw options.

**To Reproduce**
1. Try depositing small amount of fake-Ray (10)
2. Select `withdraw I` and withdraw small amount that would trigger a `Error Message: Amount is too small to perform withdrawal.`
3. Check your balance in the UI without refreshing the webapp

**Expected behavior**
The balance is expected to be taken out from withdrawal after a successful transaction

**Comment by doozenwhale** [comment]
thank you @jmarrr, good catch! I believe when we release this [fix](https://github.com/Jungle-Finance/dapp-support/issues/4) for the 3 redeem/withdraw pages, the front end would have stopped you from sending the tx in the first place. Second, when we turn off pre-flight tx checks, the gui would show failed tx's as failed, instead of successful, and your displayed user balance will revert to what it was upon failure.

I will leave this open for now for @Chasewhip8 to review.

**Comment by Chasewhip8** [comment]
Fixed in latest public release

**Comment by jmarrr** [comment]
@Chasewhip8 I just checked this behavior with the latest it still happen
